#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check if package.json is being committed
if git diff --cached --name-only | grep -q "package.json"; then
  echo "📦 Version change detected. Updating screenshot..."
  ./scripts/screen.sh
  
  if [ $? -eq 0 ]; then
    git add assets/screenshot.png
    echo "📸 Screenshot updated and added to commit."
  else
    echo "⚠️ Failed to capture screenshot. Proceeding without update."
  fi
fi
